test terraform deployment - from local
pgressa/oraclecloud-cloudnative pull request #27
Opened 2021-04-28 16:27 UTC by pgressa

2021-05-12 09:02 UTC, graemerocher requested changes

2021-05-13 07:47 UTC, pgressa commented on src/api/src/main/resources/application.yml
> +      redis:
ok

2021-05-13 07:47 UTC, pgressa commented on src/api/build.gradle
> +    testCompile "com.github.kstyrc:embedded-redis:0.6"
ok

2021-05-13 07:47 UTC, pgressa commented on src/api/src/main/java/api/services/ConfigService.java
> +    Single<Map<String, Object>> getConfig(HttpRequest<?> request) {
ok

2021-05-14 07:27 UTC, merged